# -*- coding: utf-8 -*-
"""Movie Ratings Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fmpwvcEqBzm0yVv6gM-DfYNg77DmOi6x
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json
import warnings
warnings.filterwarnings('ignore')

print("=== Movie Ratings Analysis Project ===")
print("Upload tmdb_5000_movies.csv and tmdb_5000_credits.csv before running")

# Load Data
movies_df = pd.read_csv('tmdb_5000_movies.csv')
credits_df = pd.read_csv('tmdb_5000_credits.csv')

print(f"Movies shape: {movies_df.shape}")
print(f"Credits shape: {credits_df.shape}")
print(f"Movies columns: {list(movies_df.columns)}")

# Safe director extraction function
def get_director(crew_data):
    if pd.isna(crew_data):
        return np.nan
    try:
        crew = json.loads(crew_data)
        for person in crew:
            if person.get('job') == 'Director':
                return person['name']
        return np.nan
    except:
        return np.nan

# Parse essential features
movies_df['release_year'] = pd.to_datetime(movies_df['release_date'], errors='coerce').dt.year
movies_df['genres'] = movies_df['genres'].apply(lambda x: [d['name'] for d in json.loads(x)] if pd.notna(x) else [])
movies_df['primary_genre'] = movies_df['genres'].apply(lambda x: x[0] if x else np.nan)

# Merge with credits for directors
credits_df['director'] = credits_df['crew'].apply(get_director)
movies = movies_df.merge(credits_df[['movie_id', 'director']], left_on='id', right_on='movie_id', how='left')

# Select and clean data
key_columns = ['title', 'vote_average', 'budget', 'revenue', 'primary_genre', 'director', 'release_year']
movies_clean = movies[key_columns].copy()

# Convert numeric columns safely
movies_clean['budget'] = pd.to_numeric(movies_clean['budget'], errors='coerce')
movies_clean['revenue'] = pd.to_numeric(movies_clean['revenue'], errors='coerce')
movies_clean = movies_clean.dropna()

print(f"\nClean dataset shape: {movies_clean.shape}")
print("\nFirst few rows:")
print(movies_clean.head())
print("\nData types:")
print(movies_clean.dtypes)

# === TASK 1: Load and Inspect Data ===
print("\n=== 1. DATA INSPECTION ===")
print(f"Dataset shape: {movies_clean.shape}")
print("\nMissing values:")
print(movies_clean.isnull().sum())
print("\nDataset preview:")
print(movies_clean.describe())

# === TASK 2: Statistical Analysis with NumPy ===
print("\n=== 2. NUMPY STATISTICAL ANALYSIS ===")
ratings_array = movies_clean['vote_average'].values
print(f"Ratings: Mean={np.mean(ratings_array):.2f}, Median={np.median(ratings_array):.2f}, Std={np.std(ratings_array):.2f}")

budget_array = movies_clean['budget'].values
revenue_array = movies_clean['revenue'].values
print(f"Budget: Mean=${np.mean(budget_array):,.0f}, Std=${np.std(budget_array):,.0f}")
print(f"Revenue: Mean=${np.mean(revenue_array):,.0f}, Std=${np.std(revenue_array):,.0f}")

# === TASK 3: Grouped Analysis with Pandas ===
print("\n=== 3. PANDAS GROUPED ANALYSIS ===")

# By Genre
genre_ratings = movies_clean.groupby('primary_genre')['vote_average'].agg(['mean', 'count']).round(2)
print("Average ratings by genre (top 10):")
print(genre_ratings.nlargest(10, 'mean'))

# By Director (min 2 movies)
director_ratings = movies_clean.groupby('director')['vote_average'].agg(['mean', 'count']).round(2)
director_filtered = director_ratings[director_ratings['count'] >= 2]
print("\nAverage ratings by director (top 10, min 2 movies):")
print(director_filtered.nlargest(10, 'mean'))

# By Year
year_ratings = movies_clean.groupby('release_year')['vote_average'].agg(['mean', 'count']).round(2)
print("\nRating trends by year (2005-2015 sample):")
print(year_ratings.loc[2005:2015])

# === TASK 4: Visualizations ===
fig, axes = plt.subplots(2, 3, figsize=(20, 14))
fig.suptitle('Movie Ratings Analysis Dashboard', fontsize=16)

# 1. Bar: Avg rating by genre
top_genres = genre_ratings.nlargest(10, 'mean')
axes[0,0].bar(range(len(top_genres)), top_genres['mean'], color='skyblue', edgecolor='navy')
axes[0,0].set_title('Avg Rating by Genre (Top 10)')
axes[0,0].set_xticks(range(len(top_genres)))
axes[0,0].set_xticklabels(top_genres.index, rotation=45, ha='right')
axes[0,0].set_ylabel('Avg Rating')

# 2. Bar: Avg rating by director
top_directors = director_filtered.nlargest(10, 'mean')
axes[0,1].bar(range(len(top_directors)), top_directors['mean'], color='lightcoral', edgecolor='darkred')
axes[0,1].set_title('Avg Rating by Director (Top 10)')
axes[0,1].set_xticks(range(len(top_directors)))
axes[0,1].set_xticklabels(top_directors.index, rotation=45, ha='right')
axes[0,1].set_ylabel('Avg Rating')

# 3. Line: Ratings over time
years_plot = year_ratings[year_ratings.index >= 2000]
axes[0,2].plot(years_plot.index, years_plot['mean'], marker='o', linewidth=2.5, markersize=6, color='green')
axes[0,2].set_title('Avg Ratings Over Years')
axes[0,2].set_xlabel('Year')
axes[0,2].set_ylabel('Avg Rating')
axes[0,2].grid(True, alpha=0.3)

# 4. Scatter: Budget vs Rating
axes[1,0].scatter(movies_clean['budget']/1e6, movies_clean['vote_average'],
                 alpha=0.6, s=40, color='purple')
axes[1,0].set_title('Budget vs Avg Rating')
axes[1,0].set_xlabel('Budget ($M)')
axes[1,0].set_ylabel('Avg Rating')
axes[1,0].grid(True, alpha=0.3)

# 5. Scatter: Revenue vs Rating
axes[1,1].scatter(movies_clean['revenue']/1e6, movies_clean['vote_average'],
                 alpha=0.6, s=40, color='orange')
axes[1,1].set_title('Revenue vs Avg Rating')
axes[1,1].set_xlabel('Revenue ($M)')
axes[1,1].set_ylabel('Avg Rating')
axes[1,1].grid(True, alpha=0.3)

# 6. Horizontal Bar: Top movies
top10_movies = movies_clean.nlargest(10, 'vote_average')[['title', 'vote_average']]
y_pos = np.arange(len(top10_movies))
axes[1,2].barh(y_pos, top10_movies['vote_average'], color='gold', edgecolor='darkgoldenrod')
axes[1,2].set_title('Top 10 Rated Movies')
axes[1,2].set_xlabel('Rating')
axes[1,2].set_yticks(y_pos)
axes[1,2].set_yticklabels(top10_movies['title'], fontsize=9)
axes[1,2].grid(axis='x', alpha=0.3)

plt.tight_layout()
plt.savefig('movie_dashboard.png', dpi=300, bbox_inches='tight')
plt.show()

